//! Image format detection and decoding for Mocha Browser.
//!
//! This is a thin, honest wrapper over the third-party [`image`] crate (PNG and
//! JPEG only). It detects the format from the bytes, validates it by fully
//! decoding, and reports the intrinsic pixel dimensions. Mocha does **not** write
//! an image decoder from scratch, and does **not** rasterize to a window — the
//! decoded dimensions feed replaced-element layout and a `DrawImage` display
//! command. Unsupported formats and decode failures are clear errors.

use std::io::Cursor;

use mocha_error::{MochaError, MochaResult};

/// A supported, decoded image format.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImageFormat {
    /// PNG.
    Png,
    /// JPEG.
    Jpeg,
}

/// A successfully decoded image: its format and intrinsic pixel dimensions.
///
/// Pixel data is intentionally not retained: there is no raster surface in this
/// milestone, and layout/paint only need the dimensions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecodedImage {
    /// Intrinsic width in pixels.
    pub width: u32,
    /// Intrinsic height in pixels.
    pub height: u32,
    /// The detected format.
    pub format: ImageFormat,
}

/// Detect, validate, and decode `bytes`, returning the image's intrinsic
/// dimensions and format.
///
/// Returns [`MochaError::UnsupportedFeature`] for a recognised-but-unsupported
/// format (anything other than PNG/JPEG) and [`MochaError::Image`] for unreadable
/// or corrupt data.
pub fn decode(bytes: &[u8]) -> MochaResult<DecodedImage> {
    let reader = image::ImageReader::new(Cursor::new(bytes))
        .with_guessed_format()
        .map_err(|error| MochaError::Image(format!("could not read image: {error}")))?;

    let format = match reader.format() {
        Some(image::ImageFormat::Png) => ImageFormat::Png,
        Some(image::ImageFormat::Jpeg) => ImageFormat::Jpeg,
        Some(other) => {
            return Err(MochaError::UnsupportedFeature(format!(
                "image format {other:?} is not supported (only PNG and JPEG)"
            )))
        }
        None => {
            return Err(MochaError::Image(
                "could not determine the image format".to_string(),
            ))
        }
    };

    let decoded = reader
        .decode()
        .map_err(|error| MochaError::Image(format!("could not decode image: {error}")))?;

    Ok(DecodedImage {
        width: decoded.width(),
        height: decoded.height(),
        format,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal valid 2x2 PNG (RGBA), generated by the `image` crate at test time
    /// so no binary asset is checked in here.
    fn sample_png() -> Vec<u8> {
        let mut buffer = Vec::new();
        let img = image::RgbaImage::from_pixel(2, 2, image::Rgba([10, 20, 30, 255]));
        image::DynamicImage::ImageRgba8(img)
            .write_to(&mut Cursor::new(&mut buffer), image::ImageFormat::Png)
            .unwrap();
        buffer
    }

    fn sample_jpeg() -> Vec<u8> {
        let mut buffer = Vec::new();
        let img = image::RgbImage::from_pixel(4, 3, image::Rgb([200, 100, 50]));
        image::DynamicImage::ImageRgb8(img)
            .write_to(&mut Cursor::new(&mut buffer), image::ImageFormat::Jpeg)
            .unwrap();
        buffer
    }

    #[test]
    fn decodes_png_dimensions() {
        let decoded = decode(&sample_png()).unwrap();
        assert_eq!((decoded.width, decoded.height), (2, 2));
        assert_eq!(decoded.format, ImageFormat::Png);
    }

    #[test]
    fn decodes_jpeg_dimensions() {
        let decoded = decode(&sample_jpeg()).unwrap();
        assert_eq!((decoded.width, decoded.height), (4, 3));
        assert_eq!(decoded.format, ImageFormat::Jpeg);
    }

    #[test]
    fn rejects_non_image_bytes() {
        let error = decode(b"this is definitely not an image").unwrap_err();
        assert!(matches!(
            error,
            MochaError::Image(_) | MochaError::UnsupportedFeature(_)
        ));
    }

    #[test]
    fn rejects_corrupt_png() {
        // A valid PNG signature followed by garbage: detected as PNG, fails decode.
        let mut bytes = vec![0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
        bytes.extend_from_slice(b"corrupt chunk data that is not a valid IHDR");
        assert!(matches!(decode(&bytes).unwrap_err(), MochaError::Image(_)));
    }
}
