//! Image format detection and decoding for Mocha Browser.
//!
//! This is a thin, honest wrapper over the third-party [`image`] crate (PNG and
//! JPEG only). It detects the format from the bytes, validates it by fully
//! decoding, and reports the intrinsic pixel dimensions ([`decode`]) or the full
//! RGBA pixels ([`decode_rgba`], used by the Milestone 11 software rasterizer).
//! Mocha does **not** write an image decoder from scratch. Unsupported formats
//! and decode failures are clear errors.

use std::io::Cursor;

use mocha_error::{MochaError, MochaResult};

/// A supported, decoded image format.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImageFormat {
    /// PNG.
    Png,
    /// JPEG.
    Jpeg,
}

/// A successfully decoded image: its format and intrinsic pixel dimensions.
///
/// Pixel data is intentionally not retained here; layout/paint only need the
/// dimensions. The Milestone 11 rasterizer uses [`decode_rgba`] /
/// [`RasterImage`] when it actually needs pixels.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecodedImage {
    /// Intrinsic width in pixels.
    pub width: u32,
    /// Intrinsic height in pixels.
    pub height: u32,
    /// The detected format.
    pub format: ImageFormat,
}

/// A decoded image with its RGBA8 pixels (row-major, 4 bytes per pixel), for the
/// software rasterizer. `rgba.len() == width * height * 4`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RasterImage {
    /// Intrinsic width in pixels.
    pub width: u32,
    /// Intrinsic height in pixels.
    pub height: u32,
    /// RGBA8 pixels, row-major (top-left first), 4 bytes per pixel.
    pub rgba: Vec<u8>,
}

/// Detect and validate `bytes`, returning the format and the fully decoded image.
///
/// Returns [`MochaError::UnsupportedFeature`] for a recognised-but-unsupported
/// format (anything other than PNG/JPEG) and [`MochaError::Image`] for unreadable
/// or corrupt data.
fn decode_dynamic(bytes: &[u8]) -> MochaResult<(ImageFormat, image::DynamicImage)> {
    let reader = image::ImageReader::new(Cursor::new(bytes))
        .with_guessed_format()
        .map_err(|error| MochaError::Image(format!("could not read image: {error}")))?;

    let format = match reader.format() {
        Some(image::ImageFormat::Png) => ImageFormat::Png,
        Some(image::ImageFormat::Jpeg) => ImageFormat::Jpeg,
        Some(other) => {
            return Err(MochaError::UnsupportedFeature(format!(
                "image format {other:?} is not supported (only PNG and JPEG)"
            )))
        }
        None => {
            return Err(MochaError::Image(
                "could not determine the image format".to_string(),
            ))
        }
    };

    let decoded = reader
        .decode()
        .map_err(|error| MochaError::Image(format!("could not decode image: {error}")))?;
    Ok((format, decoded))
}

/// Detect, validate, and decode `bytes`, returning the image's intrinsic
/// dimensions and format (no pixels).
pub fn decode(bytes: &[u8]) -> MochaResult<DecodedImage> {
    let (format, decoded) = decode_dynamic(bytes)?;
    Ok(DecodedImage {
        width: decoded.width(),
        height: decoded.height(),
        format,
    })
}

/// Detect, validate, and decode `bytes` into RGBA8 pixels for rasterization.
pub fn decode_rgba(bytes: &[u8]) -> MochaResult<RasterImage> {
    let (_, decoded) = decode_dynamic(bytes)?;
    let rgba = decoded.to_rgba8();
    Ok(RasterImage {
        width: rgba.width(),
        height: rgba.height(),
        rgba: rgba.into_raw(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal valid 2x2 PNG (RGBA), generated by the `image` crate at test time
    /// so no binary asset is checked in here.
    fn sample_png() -> Vec<u8> {
        let mut buffer = Vec::new();
        let img = image::RgbaImage::from_pixel(2, 2, image::Rgba([10, 20, 30, 255]));
        image::DynamicImage::ImageRgba8(img)
            .write_to(&mut Cursor::new(&mut buffer), image::ImageFormat::Png)
            .unwrap();
        buffer
    }

    fn sample_jpeg() -> Vec<u8> {
        let mut buffer = Vec::new();
        let img = image::RgbImage::from_pixel(4, 3, image::Rgb([200, 100, 50]));
        image::DynamicImage::ImageRgb8(img)
            .write_to(&mut Cursor::new(&mut buffer), image::ImageFormat::Jpeg)
            .unwrap();
        buffer
    }

    #[test]
    fn decodes_png_dimensions() {
        let decoded = decode(&sample_png()).unwrap();
        assert_eq!((decoded.width, decoded.height), (2, 2));
        assert_eq!(decoded.format, ImageFormat::Png);
    }

    #[test]
    fn decodes_jpeg_dimensions() {
        let decoded = decode(&sample_jpeg()).unwrap();
        assert_eq!((decoded.width, decoded.height), (4, 3));
        assert_eq!(decoded.format, ImageFormat::Jpeg);
    }

    #[test]
    fn decode_rgba_returns_pixels() {
        let raster = decode_rgba(&sample_png()).unwrap();
        assert_eq!((raster.width, raster.height), (2, 2));
        assert_eq!(raster.rgba.len(), 2 * 2 * 4);
        // The sample is a solid colour; the first pixel matches.
        assert_eq!(&raster.rgba[0..4], &[10, 20, 30, 255]);
    }

    #[test]
    fn rejects_non_image_bytes() {
        let error = decode(b"this is definitely not an image").unwrap_err();
        assert!(matches!(
            error,
            MochaError::Image(_) | MochaError::UnsupportedFeature(_)
        ));
    }

    #[test]
    fn rejects_corrupt_png() {
        // A valid PNG signature followed by garbage: detected as PNG, fails decode.
        let mut bytes = vec![0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
        bytes.extend_from_slice(b"corrupt chunk data that is not a valid IHDR");
        assert!(matches!(decode(&bytes).unwrap_err(), MochaError::Image(_)));
    }
}
