//! The layout box tree data model.

use mocha_style::{Color, ControlBox, NodeId};

use crate::geometry::Rect;

/// What a [`LayoutBox`] represents.
///
/// `AnonymousBlock`, `LineBox`, and `TextRun` boxes do not correspond to a DOM
/// element, so their [`LayoutBox::node_id`] is `None`.
#[derive(Debug, Clone, PartialEq)]
pub enum LayoutBoxKind {
    /// A block-level box generated by a block element.
    Block,
    /// An inline-level box generated by an inline element. Inline element content
    /// is currently flattened into [`LayoutBoxKind::TextRun`]s, so this variant is
    /// reserved and not produced by the current layout pass.
    Inline,
    /// An anonymous block box wrapping a run of inline content that sits among
    /// block siblings.
    AnonymousBlock,
    /// A single line within an inline formatting context. Contains text runs.
    LineBox,
    /// A run of text on a line, carrying its rendered string.
    TextRun(String),
    /// A replaced element (`<img>`), carrying the id of its decoded image. The
    /// box's `rect` is where the image is drawn.
    Image(usize),
    /// A form control (`<input>`, `<button>`, `<textarea>`, `<select>`),
    /// carrying the resolved control data paint needs. The box's `rect` is where
    /// the control is drawn.
    Control(ControlBox),
}

/// A node in the layout tree with computed geometry and the style fields paint
/// needs (so `mocha_paint` depends on neither `mocha_css` nor `mocha_style`).
#[derive(Debug, Clone, PartialEq)]
pub struct LayoutBox {
    /// The source DOM node, or `None` for anonymous/line/text-run boxes.
    pub node_id: Option<NodeId>,
    /// The kind of box.
    pub kind: LayoutBoxKind,
    /// The border-box geometry (for text runs, the text's box).
    pub rect: Rect,
    /// Font size in pixels.
    pub font_size: f32,
    /// Text/foreground color.
    pub color: Color,
    /// Background color (`a == 0` means transparent / no fill).
    pub background_color: Color,
    /// Border width in pixels (0 means no border).
    pub border_width: f32,
    /// Border color.
    pub border_color: Color,
    /// Corner radius in pixels (0 means square corners).
    pub border_radius: f32,
    /// Child boxes in document order.
    pub children: Vec<LayoutBox>,
}

impl LayoutBox {
    /// An anonymous structural box (no node, no styling) of the given kind.
    pub(crate) fn anonymous(
        kind: LayoutBoxKind,
        rect: Rect,
        children: Vec<LayoutBox>,
    ) -> LayoutBox {
        LayoutBox {
            node_id: None,
            kind,
            rect,
            font_size: 0.0,
            color: Color::BLACK,
            background_color: Color::TRANSPARENT,
            border_width: 0.0,
            border_color: Color::BLACK,
            border_radius: 0.0,
            children,
        }
    }
}
